# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iip_processing_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscription_id', models.CharField(blank=True, max_length=8)),
                ('modified_datetime', models.DateTimeField(auto_now_add=True)),
                ('status_summary', models.CharField(blank=True, max_length=20)),
                ('status_detail', models.TextField(blank=True)),
            ],
        ),
    ]
