# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iip_processing_app', '0002_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Processing Statuses'},
        ),
        migrations.AlterField(
            model_name='status',
            name='modified_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
